windowrule = float on, center on, stay_focused on, size 1000 1000, match:class Alacritty
windowrule = float on, center on, stay_focused on, size (window_w*0.5) (window_h*0.5), match:class kitty-dropterm
windowrule = float on, center on, stay_focused on, size (window_w*0.2) (window_h*0.2), match:class neomutt1
windowrule = float on, center on, stay_focused on, size (window_w*0.2) (window_h*0.2), match:class kitty-cmus
windowrule = float on, center on, stay_focused on, size (window_w*0.2) (window_h*0.1), match:class ranger
windowrule = float on, center on, pin on, stay_focused on, size 1000 1000, match:class org.pulseaudio.pavucontrol

 windowrule =   match:class kitty-weechat, workspace 6
 windowrule =   match:class kitty, match:title weechat, workspace 6
 windowrule =   match:class kitty, workspace 3
 windowrule =   match:class floorp, workspace 2
 windowrule =   match:class kitty-nvim, workspace 5
 windowrule =   match:class kitty-tasks, workspace 7

# 1. Apply to anonymous layers (screenshot selection)
layerrule = match:namespace ^$, animation off
layerrule = match:namespace ^$, blur off
layerrule = match:namespace ^$, ignore_alpha 0

# 2. Re-apply blur to Waybar (overriding the catch-all)
layerrule = match:namespace ^waybar$, blur on
layerrule = match:namespace ^waybar$, ignore_alpha 0.5
